global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'ingestor'
    static_configs:
      - targets: ['ingestor:8000']

  - job_name: 'processor'
    static_configs:
      - targets: ['processor:8001']
